### ISSUE TITLE
Investigate `RetryPolicy#recovering` API

### ISSUE THREAD

**Issue by adelbertc** [adelbertc/rebind#2]
`RetryPolicy#recovering` is a bit weird in that the `Count` for each error is across all errors. For instance, if we have `A` mapped to `2.times` and `B` mapped to `1.time` and the action fails with `A` twice and then with `B`, one might expect it to be retried one more time since `B` is mapped to `1.time`, but the current behavior shows that in total we've already tried 2 times which is greater than 1, and it stops.

Bit of code responsible is [here](https://github.com/adelbertc/rebind/blob/bc231791ecc1d2a640fcbfc64baaae27ba6373f4/src/main/scala/rebind/RetryPolicy.scala#L72), specifically the `handler(e) > n` bit.

**Comment by adelbertc** [comment]
Some code:

``` scala
import rebind._
import rebind.Rebind._

import scala.concurrent.duration._

import scalaz.DisjunctionT
import scalaz.effect.{ IO, SafeApp }

object Example extends SafeApp {
  sealed abstract class UhOh
  final case object A extends UhOh
  final case object B extends UhOh

  private var count = 0 // yeah i know
  def ew: DisjunctionT[IO, UhOh, Unit] =
    DisjunctionT.right(IO.putStrLn("Running action")).flatMap { _ =>
      if (count < 2) DisjunctionT.left(IO { count += 1; println(" A"); A }) // fail with A first 2 times
      else DisjunctionT.left(IO { count += 1; println(" B"); B }) // afterwards fail with B
    }

  override def runc: IO[Unit] = {
    val policy = exponentialBackoff(1.second) && limitRetries(3)

    policy.recovering(ew) {
      case A => 2.times
      case B => 1.time
    }.run.flatMap(_.fold(_ => IO.putStrLn("Ended with error"), _ => IO.putStrLn("Ended with success")))
  }
}
```

Output is:

```
Running action A
Running action A // result of first retry for error A - total retries = 1
Running action B // result of second retry for error A - total retries = 2
Ended with error
```

Computation stops because total retries = 2 < 1 (B's), but maybe should've retried again because we haven't retried _on_ `B` yet.

**Comment by jroesch** [comment]
cc me

**Comment by adelbertc** [comment]
https://github.com/adelbertc/rebind/issues/6 may be able to rectify this
